### ISSUE TITLE
Cannot be opened app is not notarised

### ISSUE THREAD

**Issue by iMonZ** [shemeshg/cakebrewjs#1]
Hey,

your app cannot be opened because it's not notarized.

If you don't plan to change this, could you please distribute your app as a formula instead of a cask.
Then this error would disappear too.

Thanks

**Comment by iMonZ** [comment]
“cakebrewjs.app” is damaged and can’t be opened. You should move it to the Bin.

**Comment by shemeshg** [comment]
Hi

Tested on Big Sur 11.6:

I don't have Apple ID, so it is not signed, 

# Please try this 

1.
```
brew uninstall --zap cakebrewjs
brew install cakebrewjs
```
2. after the error "cannot be opened because the developer cannot be verified" with "Move to Trash" and "Cancel"
3. Press cancel
4. R.Click and Open from the awesome bar 
5. Now you will have Dialog with three buttons "Open" "Move to Trash" and "Cancel"
6. Select Open 
and it should be fine.

I see this in many other casks where developers dont have AppleID...


# Do you actually see an error  of 'cakebrewjs.app is damaged' or meant for these two dialogs I've mentioned before?

## Supposed it is damaged: 
- is https://sourceforge.net/projects/cakebrewjs/files/v1.0.0/#:~:text=cakebrewjs-1.0.0-mac.zip also damaged?
- Do you think it is the electron packager ( OSX version OSX11 vs OSX10 )?



I'm not sure packaging electron in formula is that common. I'll have to research that do you have an example?
